language: node_js
node_js:
 - "4.1"

branches:
  only:
    - master

before_script:
  - npm install -g bower gulp del gulp-angular-templatecache gulp-autoprefixer gulp-bytediff gulp-concat gulp-filter gulp-inject gulp-jscs gulp-jshint gulp-minify-css gulp-minify-html gulp-notify gulp-ng-annotate gulp-rev gulp-rev-replace gulp-task-listing gulp-uglify jshint-stylish merge-stream

script:
  - npm install
  - bower install
  - gulp build

cache:
  directories:
    - bower_components
    - node_modules

notifications:
  email:
    - tuomas.jaakola@iki.fi
