language: node_js
node_js:
 - "4.1"

branches:
  only:
    - master

before_install:
  - npm install -g gulp
  - npm install -g gulp-load-plugins
  - npm install -g gulp-jshint
  - npm install -g gulp-uglify

script:
  - npm install
  - gulp js

cache:
  directories:
    - node_modules

notifications:
  email:
    - tuomas.jaakola@iki.fi
